use_gpu: True
device: 3
outdir: Result/llama_dolly_fft
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 6
  total_round_num: 400
  save_to: "checkpoints/llama.dolly-meta.lora.ckpt"
  save_freq: 500
  make_global_eval: True
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'dolly-15k@llm'
  splits: [0.99, 0.0, 0.01]
  splitter: 'meta'
llm:
  tok_len: 650
  chat:
    max_len: 1000
  offsite_tuning:
    use: False
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'fft', n_frequency: 600000, scaling: 300.0, default: 777} ]
dataloader:
  batch_size: 5
model:
  type: 'baffo32/decapoda-research-llama-7B-hf@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 0.05
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 100
  metrics: ['acc','loss']
  best_res_update_round_wise_key: 'test_loss'
  # metrics: ['acc']
  report: ["acc",'weighted_avg', 'avg', 'raw']
expname: "llm-baselines/llama-7b_dolly-meta_lora"
# wandb:
#   use: True
#   name_user: 'harliwu'
#   name_project: 'llama-7b_dolly-meta_lora'