use_gpu: True
device: 1
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 4
  total_round_num: 1
  save_to: "checkpoints/llama.gsm.fft.one.ckpt"
  save_freq: 500
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'gsm8k@llm'
  splits: [0.998,0.001,0.001]
  splitter: 'lda'
llm:
  tok_len: 680
  chat:
    max_len: 1000
  offsite_tuning:
    use: False
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'fft', n_frequency: 6000, scaling: 150.0, 'target_modules':'.*self_attn.q_proj$'} ]
dataloader:
  batch_size: 2
model:
  type: 'Qwen/Qwen2.5-7B-Instruct@huggingface_llm'
train:
  local_update_steps: 3000
  batch_or_epoch: batch
  optimizer:
    lr: 0.005
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 100
  metrics: ['loss']
  best_res_update_round_wise_key: 'val_loss'
  report: ['weighted_avg', 'avg', 'raw']
expname: "qwen/gsm8k/fft-one"
# wandb:
#   use: True
#   name_user: 'harliwu'
#   name_project: 'llama-7b_gsm8k_offsite-tuning'